export class ModelPaper {
  id?: number;  // Make id optional as it is generated by the backend
  grade: string;
  category: string;
  paperNo: string;
  partNo: string;
  description: string;  // Description can be optional

  constructor(
    grade: string, category: string, paperNo: string, partNo: string, description: string = '' ) {
    this.grade = grade;
    this.category = category;
    this.paperNo = paperNo;
    this.partNo = partNo;
    this.description = description;
  }
}
